### ISSUE TITLE
Join Request

### ISSUE THREAD

**Issue by ThePennitentOne** [LubieKakao1212/GGJ2023-Powidlo#2]
By the name of the great jammers, with the act of a submitting a form I invoke the  rite of code collaboration, Listen o managers of this grand repository and hear my willful proclamation. Now I beseech thee: grant me access to this divine realm of knowledge and allow me to walk alongside you. So i may bring glory for the great jam now and forever

**Comment by LubieKakao1212** [comment]
If you say so than: No

**Comment by ThePennitentOne** [comment]
Ah, so I am still not worthy… all the time committed, all the blood shed in your name and yet still that is not enough?
What more you ask of me?
